version: '3.8'

services:
  redis-server:
    container_name: my-redis-container
    image: redis:alpine
    restart: unless-stopped
    ports: 
      - "6379:6379"

    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./redis_data:/data

  redis-gui:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped 
    environment:
      - REDIS_HOSTS=local:redis-server:6379:0:${REDIS_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - redis-server
    
    